vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        visite:
            uri_prefix: /images/visites
            upload_destination: '%kernel.project_dir%/public/images/visites'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false  # Évite d'injecter les fichiers au chargement de l'entité
            delete_on_update: true  # Supprime l'ancien fichier lors d'une mise à jour
            delete_on_remove: true  # Supprime le fichier associé lorsque l'entité est supprimée
